/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jonrryenamorado_examen2;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author wende
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        au.cargarArchivo();
        System.out.println("user = rutten\npass = 123");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_users = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_users = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jd_newuser = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        tf_password = new javax.swing.JPasswordField();
        jd_albums = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_albums = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        cb_delalbum = new javax.swing.JComboBox<album>();
        jd_newalbum = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_alname = new javax.swing.JTextField();
        tf_alart = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jd_newsong = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_songname = new javax.swing.JTextField();
        tf_songgenero = new javax.swing.JTextField();
        cb_albumsong = new javax.swing.JComboBox<>();
        sp_duracion = new javax.swing.JSpinner();
        jButton13 = new javax.swing.JButton();
        jd_login = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_logname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_logpass = new javax.swing.JPasswordField();
        jButton15 = new javax.swing.JButton();
        jd_submenu = new javax.swing.JDialog();
        jButton16 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        user_actual = new javax.swing.JLabel();
        jd_explorar = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        cb_albumsexplorar = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_songs = new javax.swing.JList<>();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jd_playlist = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_playlists = new javax.swing.JTree();
        jButton23 = new javax.swing.JButton();
        jd_favs = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_favs = new javax.swing.JList<>();
        jButton24 = new javax.swing.JButton();
        jd_play = new javax.swing.JDialog();
        jlb_time = new javax.swing.JLabel();
        pgb_time = new javax.swing.JProgressBar();
        jlb_song = new javax.swing.JLabel();
        jd_s_to_p = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_añadiraplaylist = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("USERS");

        jButton7.setText("New");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Delete");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jl_users);

        jLabel3.setText("Users en Archivo");

        jButton11.setText("Reload List");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_usersLayout = new javax.swing.GroupLayout(jd_users.getContentPane());
        jd_users.getContentPane().setLayout(jd_usersLayout);
        jd_usersLayout.setHorizontalGroup(
            jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_usersLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addGap(31, 31, 31)
                .addComponent(jButton11)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_usersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_usersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(133, 133, 133))
        );
        jd_usersLayout.setVerticalGroup(
            jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setText("NOMBRE:");

        jLabel5.setText("EDAD:");

        jLabel6.setText("USERNAME:");

        jLabel7.setText("PASSWORD:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("NEW USER");

        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });

        jButton10.setText("Guardar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_newuserLayout = new javax.swing.GroupLayout(jd_newuser.getContentPane());
        jd_newuser.getContentPane().setLayout(jd_newuserLayout);
        jd_newuserLayout.setHorizontalGroup(
            jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_newuserLayout.createSequentialGroup()
                .addGroup(jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_newuserLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_name)
                            .addComponent(tf_edad)
                            .addComponent(tf_username)
                            .addComponent(tf_password)))
                    .addGroup(jd_newuserLayout.createSequentialGroup()
                        .addContainerGap(103, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(101, 101, 101))
            .addGroup(jd_newuserLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_newuserLayout.setVerticalGroup(
            jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newuserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(25, 25, 25))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("ALBUMS");

        jt_albums.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Album", "Album 2", "Album 3", "Album 4"
            }
        ));
        jScrollPane1.setViewportView(jt_albums);

        jButton9.setText("Crear");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton12.setText("Eliminar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        cb_delalbum.setModel(new DefaultComboBoxModel<album>()
        );

        javax.swing.GroupLayout jd_albumsLayout = new javax.swing.GroupLayout(jd_albums.getContentPane());
        jd_albums.getContentPane().setLayout(jd_albumsLayout);
        jd_albumsLayout.setHorizontalGroup(
            jd_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_albumsLayout.createSequentialGroup()
                .addGroup(jd_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_albumsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9)
                        .addGap(142, 142, 142)
                        .addComponent(cb_delalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_albumsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(248, 248, 248))
        );
        jd_albumsLayout.setVerticalGroup(
            jd_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_albumsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jd_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton12)
                    .addComponent(cb_delalbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel10.setText("NOMBRE:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("NEW ALBUM");

        jLabel12.setText("ARTISTA:");

        jButton14.setText("Guardar");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_newalbumLayout = new javax.swing.GroupLayout(jd_newalbum.getContentPane());
        jd_newalbum.getContentPane().setLayout(jd_newalbumLayout);
        jd_newalbumLayout.setHorizontalGroup(
            jd_newalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_newalbumLayout.createSequentialGroup()
                .addGroup(jd_newalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_newalbumLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jd_newalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_newalbumLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tf_alart))
                            .addGroup(jd_newalbumLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(tf_alname))))
                    .addGroup(jd_newalbumLayout.createSequentialGroup()
                        .addContainerGap(100, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(72, 72, 72))
            .addGroup(jd_newalbumLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_newalbumLayout.setVerticalGroup(
            jd_newalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newalbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_newalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_newalbumLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10))
                    .addComponent(tf_alname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_newalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_alart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("NEW SONG");

        jLabel14.setText("NOMBRE:");

        jLabel16.setText("DURACION:");

        jLabel17.setText("GENERO:");

        jLabel18.setText("PERTENECE A:");

        sp_duracion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButton13.setText("Guardar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_newsongLayout = new javax.swing.GroupLayout(jd_newsong.getContentPane());
        jd_newsong.getContentPane().setLayout(jd_newsongLayout);
        jd_newsongLayout.setHorizontalGroup(
            jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newsongLayout.createSequentialGroup()
                .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_newsongLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel13))
                    .addGroup(jd_newsongLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_albumsong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_songgenero)
                            .addGroup(jd_newsongLayout.createSequentialGroup()
                                .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton13)
                                    .addComponent(tf_songname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jd_newsongLayout.setVerticalGroup(
            jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_newsongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_newsongLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_songname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jd_newsongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_songgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addComponent(cb_albumsong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18))
                .addGap(50, 50, 50)
                .addComponent(jButton13)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("LOGIN");

        jLabel19.setText("USERNAME:");

        jLabel20.setText("PASSWORD:");

        jButton15.setText("Log In");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(54, 54, 54))
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_logname)
                    .addComponent(tf_logpass))
                .addContainerGap())
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(37, 37, 37)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_logname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_logpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );

        jButton16.setText("Explorar");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("TU REPRODUCTOR DE MUSICA");

        jButton17.setText("Crear Playlist");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        jButton18.setText("Ver Playlist");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });

        jButton19.setText("Ver Favoritos");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });

        jButton20.setText("Salir");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });

        jLabel22.setText("User:");

        javax.swing.GroupLayout jd_submenuLayout = new javax.swing.GroupLayout(jd_submenu.getContentPane());
        jd_submenu.getContentPane().setLayout(jd_submenuLayout);
        jd_submenuLayout.setHorizontalGroup(
            jd_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_submenuLayout.createSequentialGroup()
                .addGroup(jd_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_submenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_submenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_submenuLayout.setVerticalGroup(
            jd_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_submenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel21)
                .addGap(19, 19, 19)
                .addGroup(jd_submenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(user_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addGap(18, 18, 18)
                .addComponent(jButton18)
                .addGap(18, 18, 18)
                .addComponent(jButton19)
                .addGap(18, 18, 18)
                .addComponent(jButton20)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel23.setText("EXPLORAR");

        cb_albumsexplorar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_albumsexplorarItemStateChanged(evt);
            }
        });

        jLabel24.setText("Album:");

        jScrollPane3.setViewportView(jl_songs);

        jButton21.setText("Add to Playlist...");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });

        jButton22.setText("Add to Favorites");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_explorarLayout = new javax.swing.GroupLayout(jd_explorar.getContentPane());
        jd_explorar.getContentPane().setLayout(jd_explorarLayout);
        jd_explorarLayout.setHorizontalGroup(
            jd_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_explorarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel23)
                        .addGroup(jd_explorarLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(18, 18, 18)
                            .addComponent(cb_albumsexplorar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_explorarLayout.setVerticalGroup(
            jd_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_explorarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jd_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_albumsexplorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGroup(jd_explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_explorarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jd_explorarLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton21)
                        .addGap(18, 18, 18)
                        .addComponent(jButton22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel25.setText("PLAYLISTS");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Playlists");
        jt_playlists.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_playlists.setRootVisible(false);
        jt_playlists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_playlistsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jt_playlists);

        jButton23.setText("Eliminar");
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_playlistLayout = new javax.swing.GroupLayout(jd_playlist.getContentPane());
        jd_playlist.getContentPane().setLayout(jd_playlistLayout);
        jd_playlistLayout.setHorizontalGroup(
            jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_playlistLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_playlistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton23)
                .addContainerGap())
        );
        jd_playlistLayout.setVerticalGroup(
            jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playlistLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton23)
                .addContainerGap())
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel26.setText("FAVORITOS");

        jScrollPane5.setViewportView(jl_favs);

        jButton24.setText("Play");
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_favsLayout = new javax.swing.GroupLayout(jd_favs.getContentPane());
        jd_favs.getContentPane().setLayout(jd_favsLayout);
        jd_favsLayout.setHorizontalGroup(
            jd_favsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_favsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jd_favsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_favsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jd_favsLayout.setVerticalGroup(
            jd_favsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_favsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton24)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jlb_time.setText("0");

        jlb_song.setText("jLabel27");

        javax.swing.GroupLayout jd_playLayout = new javax.swing.GroupLayout(jd_play.getContentPane());
        jd_play.getContentPane().setLayout(jd_playLayout);
        jd_playLayout.setHorizontalGroup(
            jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgb_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jd_playLayout.createSequentialGroup()
                        .addComponent(jlb_song)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jlb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jd_playLayout.setVerticalGroup(
            jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_song)
                    .addComponent(jlb_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jl_añadiraplaylist);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setText("AÑADIR A PLAYLIST...");

        jButton25.setText("Añadir");
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_s_to_pLayout = new javax.swing.GroupLayout(jd_s_to_p.getContentPane());
        jd_s_to_p.getContentPane().setLayout(jd_s_to_pLayout);
        jd_s_to_pLayout.setHorizontalGroup(
            jd_s_to_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_s_to_pLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
            .addGroup(jd_s_to_pLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_s_to_pLayout.setVerticalGroup(
            jd_s_to_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_s_to_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jd_s_to_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Usuarios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Albums");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Canciones");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        jButton4.setText("Log In");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Guardar Usuarios");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Cargar Usuarios");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        au.cargarArchivo();
        JOptionPane.showMessageDialog(this, "Archivo Cargado!");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        au.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Archivo Guardado!");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultListModel model = new DefaultListModel();
        for (user t : au.getListauser()) {
            model.addElement(t);
        }
        jl_users.setModel(model);
        jd_users.setModal(false);
        jd_users.pack();
        jd_users.setLocationRelativeTo(this);
        jd_users.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:

        au.setUser(new user(tf_name.getText(), tf_edad.getText(), tf_username.getText(), tf_password.getText()));
        au.escribirArchivo();
        JOptionPane.showMessageDialog(jd_newuser, "Usuario guardado en ARRAYLIST y en ARCHIVO");
        reloaduser();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        jd_newuser.setModal(false);
        jd_newuser.pack();
        jd_newuser.setLocationRelativeTo(this);
        jd_newuser.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        DefaultListModel model = new DefaultListModel();
        for (user t : au.getListauser()) {
            model.addElement(t);
        }
        jl_users.setModel(model);
    }//GEN-LAST:event_jButton11MouseClicked
    public void reloaduser() {
        DefaultListModel model = new DefaultListModel();
        for (user t : au.getListauser()) {
            model.addElement(t);
        }
        jl_users.setModel(model);
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        llenartable();
        llenarcombodeletealbum();
        jd_albums.setModal(false);
        jd_albums.pack();
        jd_albums.setLocationRelativeTo(this);
        jd_albums.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        albums.add(new album(tf_alname.getText(), tf_alart.getText()));
        llenartable();
        llenarcombodeletealbum();
        JOptionPane.showMessageDialog(jd_newalbum, "Creado exitosamente!");
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        jd_newalbum.setModal(false);
        jd_newalbum.pack();
        jd_newalbum.setLocationRelativeTo(this);
        jd_newalbum.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        try {

            for (album t : albums) {
                if (t == cb_delalbum.getSelectedItem()) {
                    albums.remove(t);
                }
            }
            llenartable();
            llenarcombodeletealbum();
            JOptionPane.showMessageDialog(jd_albums, "Eliminado con exito!");
        } catch (Exception e) {
            for (album t : albums) {
                if (t == cb_delalbum.getSelectedItem()) {
                    albums.remove(t);
                }
            }
            llenartable();
            llenarcombodeletealbum();
            JOptionPane.showMessageDialog(jd_albums, "Eliminado con exito!");
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        album temp = (album) cb_albumsong.getSelectedItem();
        for (album t : albums) {
            if (t == temp) {
                albums.get(albums.indexOf(t)).getSongs().add(new song(tf_songname.getText(), t.getArtist(), (Integer) sp_duracion.getValue(), tf_songgenero.getText()));

            }
        }
        JOptionPane.showMessageDialog(jd_newsong, "Cancion Creada Exitosamente!");
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        llenarcombodeletealbum();
        jd_newsong.setModal(false);
        jd_newsong.pack();
        jd_newsong.setLocationRelativeTo(this);
        jd_newsong.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        jd_login.setModal(false);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        String name = tf_logname.getText();
        String pass = tf_logpass.getText();
        boolean ver = false;
        for (user u : au.getListauser()) {
            if (u.getUsername().equals(name) && u.getPassword().equals(pass)) {
                JOptionPane.showMessageDialog(jd_login, "Bienvenido!");
                useractual = au.getListauser().indexOf(u);

                jd_submenu.setModal(false);
                jd_submenu.pack();
                jd_submenu.setLocationRelativeTo(this);
                jd_submenu.setVisible(true);
                jd_login.setVisible(false);
                ver = true;
            }
        }
        if (!ver) {
            JOptionPane.showMessageDialog(jd_login, "Datos Incorrectos", "Nel", JOptionPane.ERROR_MESSAGE);
        }
        tf_logname.setText("");
        tf_logpass.setText("");
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:

        llenarcombodeletealbum();
        llenarlist();
        jd_explorar.setModal(false);
        jd_explorar.pack();
        jd_explorar.setLocationRelativeTo(this);
        jd_explorar.setVisible(true);
    }//GEN-LAST:event_jButton16MouseClicked

    private void cb_albumsexplorarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_albumsexplorarItemStateChanged
        // TODO add your handling code here:
        llenarlist();
    }//GEN-LAST:event_cb_albumsexplorarItemStateChanged

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        // TODO add your handling code here:
        if (jl_songs.getSelectedIndex() >= 0) {
            añadir = jl_songs.getSelectedValue();
            DefaultListModel<playlist> model = new DefaultListModel<playlist>();
            for (playlist p : au.getListauser().get(useractual).getPlaylist()) {
                model.addElement(p);
            }
            jl_añadiraplaylist.setModel(model);
            jd_s_to_p.setModal(false);
            jd_s_to_p.pack();
            jd_s_to_p.setLocationRelativeTo(this);
            jd_s_to_p.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(jd_users, "Selecciona una cancion de la lista!");
        }
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        // TODO add your handling code here:
        if (jl_songs.getSelectedIndex() >= 0) {
            au.getListauser().get(useractual).getFavoritos().add(jl_songs.getSelectedValue());
            JOptionPane.showMessageDialog(jd_explorar, "Cancion Agregada a Favoritos!");
            au.escribirArchivo();
        }else{
            JOptionPane.showMessageDialog(jd_users, "Selecciona una cancion de la lista!");
        }
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // TODO add your handling code here:
        String tmp = JOptionPane.showInputDialog("Ingresar nombre de playlist");
        try {
            
        if (tmp.isEmpty()) {

        } else {

            playlist p = new playlist(tmp);
            au.getListauser().get(useractual).getPlaylist().add(p);
            JOptionPane.showMessageDialog(jd_submenu, "Playlist Agregada!");
            au.escribirArchivo();
        }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:
        llenartree();

        jd_playlist.setModal(false);
        jd_playlist.pack();
        jd_playlist.setLocationRelativeTo(this);
        jd_playlist.setVisible(true);
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        // TODO add your handling code here:
        DefaultListModel<song> model = new DefaultListModel<song>();
        for (song s : au.getListauser().get(useractual).getFavoritos()) {
            model.addElement(s);
        }
        jl_favs.setModel(model);
        jd_favs.setModal(false);
        jd_favs.pack();
        jd_favs.setLocationRelativeTo(this);
        jd_favs.setVisible(true);
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
        // TODO add your handling code here:
        if (jl_favs.getSelectedIndex() >= 0) {
            try {
                pgb_time.setValue(0);
                hh.stop();
            } catch (Exception e) {
            }

            jlb_song.setText(jl_favs.getSelectedValue().getName());

            pgb_time.setMaximum(jl_favs.getSelectedValue().getSeconds());
            jd_play.pack();
            jd_play.setLocationRelativeTo(this);
            jd_play.setVisible(true);
            hh = new HiloHora(jlb_time, jl_favs.getSelectedValue().getSeconds(), pgb_time);
            hh.start();
        }else{
            JOptionPane.showMessageDialog(jd_users, "Selecciona una cancion de la lista!");
        }
    }//GEN-LAST:event_jButton24MouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
        // TODO add your handling code here:
        try {
            if (nodo_seleccionado.getUserObject() instanceof song) {
                song_seleccionada = (song) nodo_seleccionado.getUserObject();
                DefaultMutableTreeNode pl = (DefaultMutableTreeNode) nodo_seleccionado.getParent();
                playlist temp = (playlist) pl.getUserObject();
                DefaultTreeModel m = (DefaultTreeModel) jt_playlists.getModel();
                m.removeNodeFromParent(nodo_seleccionado);
                m.reload();
                for (playlist p : au.getListauser().get(useractual).getPlaylist()) {
                    if (p == temp) {
                        p.getSongs().remove(song_seleccionada);
                    }
                    au.getListauser().get(useractual).getPlaylist().set(au.getListauser().get(useractual).getPlaylist().indexOf(p), p);
                }
                JOptionPane.showMessageDialog(jd_playlist, "Cancion Eliminada!");
            }else{
                JOptionPane.showMessageDialog(jd_users, "Selecciona una cancion de una playlist!");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton23MouseClicked

    private void jt_playlistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_playlistsMouseClicked
        // TODO add your handling code here:
        int row = jt_playlists.getClosestRowForLocation(evt.getX(), evt.getY());
        jt_playlists.setSelectionRow(row);
        Object v1 = jt_playlists.getSelectionPath().getLastPathComponent();
        nodo_seleccionado = (DefaultMutableTreeNode) v1;
    }//GEN-LAST:event_jt_playlistsMouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        // TODO add your handling code here:
        if (jl_añadiraplaylist.getSelectedIndex() >= 0) {
            playlist temp = jl_añadiraplaylist.getSelectedValue();
            for (playlist p : au.getListauser().get(useractual).getPlaylist()) {
                if (temp == p) {
                    p.getSongs().add(añadir);
                }
            }
            JOptionPane.showMessageDialog(jd_s_to_p, "Cancion Agregada a PLaylist Exitosamente!");
        }
        else{
            JOptionPane.showMessageDialog(jd_s_to_p, "Selecciona una playlist de la lista!");
        }
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:

        try {
            if (jl_users.getSelectedIndex() >= 0) {
                user temp = jl_users.getSelectedValue();
                for (user u : au.getListauser()) {
                    if (u == temp) {
                        au.getListauser().remove(u);
                    }
                }
                JOptionPane.showMessageDialog(jd_users, "Usuario Eliminado!");
            }
            else{
                JOptionPane.showMessageDialog(jd_users, "Selecciona un usuario de la playlist!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_users, "Usuario Eliminado!");
        }
        au.escribirArchivo();
        reloaduser();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        // TODO add your handling code here:
        jd_submenu.setVisible(false);
    }//GEN-LAST:event_jButton20MouseClicked

    public void llenartree() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode();
        for (playlist p : au.getListauser().get(useractual).getPlaylist()) {
            DefaultMutableTreeNode playlist = new DefaultMutableTreeNode(p);
            for (song s : p.getSongs()) {
                DefaultMutableTreeNode song = new DefaultMutableTreeNode(s);
                playlist.add(song);
            }
            root.add(playlist);
        }
        DefaultTreeModel model = new DefaultTreeModel(root);
        jt_playlists.setModel(model);
    }

    private void llenarlist() {
        DefaultListModel<song> model = new DefaultListModel<song>();
        if (cb_albumsexplorar.getItemCount() > 0) {

            album tmp = (album) cb_albumsexplorar.getSelectedItem();

            for (song s : tmp.getSongs()) {
                model.addElement(s);
            }
            jl_songs.setModel(model);
        }

    }

    private void llenarcombodeletealbum() {
        DefaultComboBoxModel<album> model = new DefaultComboBoxModel<album>();
        for (album t : albums) {
            model.addElement(t);
        }
        cb_delalbum.setModel(model);
        cb_albumsong.setModel(model);
        cb_albumsexplorar.setModel(model);
    }

    private void llenartable() {
        DefaultTableModel model = new DefaultTableModel();
        for (album t : albums) {
            Object col = t.getName();
            ArrayList<Object> rows = new ArrayList();
            for (song s : t.getSongs()) {
                rows.add(s.getName());
            }
            model.addColumn(col, rows.toArray());
        }
        jt_albums.setModel(model);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<album> cb_albumsexplorar;
    private javax.swing.JComboBox<album> cb_albumsong;
    public javax.swing.JComboBox<album> cb_delalbum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JDialog jd_albums;
    private javax.swing.JDialog jd_explorar;
    private javax.swing.JDialog jd_favs;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_newalbum;
    private javax.swing.JDialog jd_newsong;
    private javax.swing.JDialog jd_newuser;
    private javax.swing.JDialog jd_play;
    private javax.swing.JDialog jd_playlist;
    private javax.swing.JDialog jd_s_to_p;
    private javax.swing.JDialog jd_submenu;
    private javax.swing.JDialog jd_users;
    private javax.swing.JList<playlist> jl_añadiraplaylist;
    private javax.swing.JList<song> jl_favs;
    private javax.swing.JList<song> jl_songs;
    private javax.swing.JList<user> jl_users;
    public javax.swing.JLabel jlb_song;
    public javax.swing.JLabel jlb_time;
    private javax.swing.JTable jt_albums;
    private javax.swing.JTree jt_playlists;
    public javax.swing.JProgressBar pgb_time;
    private javax.swing.JSpinner sp_duracion;
    private javax.swing.JTextField tf_alart;
    private javax.swing.JTextField tf_alname;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_logname;
    private javax.swing.JPasswordField tf_logpass;
    private javax.swing.JTextField tf_name;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_songgenero;
    private javax.swing.JTextField tf_songname;
    private javax.swing.JTextField tf_username;
    private javax.swing.JLabel user_actual;
    // End of variables declaration//GEN-END:variables
    adminUser au = new adminUser("./tali.siteamo");
    ArrayList<album> albums = new ArrayList();
    int useractual = 0;
    HiloHora hh;
    DefaultMutableTreeNode nodo_seleccionado;
    song song_seleccionada;
    song añadir;
}
